source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  #gem 'spring'
end

gem 'administrate', '~> 0.1.0'
gem 'bootstrap', git: 'https://github.com/twbs/bootstrap-rubygem'
gem 'clipboard-rails', '~> 1.4.2'
gem 'devise', '~> 3.5.2'
gem 'font-awesome-rails', '~> 4.4.0.0'
gem 'friendly_id', '~> 5.1.0'
gem 'jquery-turbolinks', '~> 2.1.0'
gem 'select2-rails', '~> 4.0.0'

source 'https://rails-assets.org' do
  gem 'rails-assets-tether', '>= 1.1.0'
end

# Enforce these so we can pull out gems that aren't compatible with the latest versions
gem 'omniauth', '~> 1.2.2'
gem 'omniauth-oauth2', '~> 1.3', '>= 1.3.1'

gem 'omniauth-23andme'
gem 'omniauth-500px'
#gem 'omniauth-affinitylive'
gem 'omniauth-amazon'
gem 'omniauth-angellist'
##gem 'omniauth-aol'
gem 'omniauth-appnet'
##gem 'omniauth-appfigures'
#gem 'omniauth-auphonic'
##gem 'omniauth-auth0'
gem 'omniauth-automatic'
##gem 'omniauth-arcgis'
#gem 'omniauth-authic'
##gem 'omniauth-azure-activedirectory'
gem 'omniauth-azure-oauth2'
##gem 'omniauth-behance'
#gem 'omniauth-bike-index'
#gem 'omniauth-thebase'
#gem 'omniauth-bigcartel'
gem 'omniauth-bitly', github: 'excid3/omniauth-bitly'
##gem 'omniauth-bitrix24'
#gem 'omniauth-box'
gem 'omniauth-box2'
#gem 'omniauth-browserid'
#gem 'omniauth-broadworks'
##gem 'omniauth-buffer'
gem 'omniauth-buffer2'
#gem 'omniauth-cacoo'
#gem 'omniauth-createsend'
##gem 'omniauth-cheddar'
gem 'omniauth-clef'
#gem 'omniauth-cloud66'
##gem 'omniauth-cloudsdale'
gem 'omniauth_cobot'
gem 'omniauth-concur'
#gem 'omniauth-uaa-oauth2'
##gem 'omniauth-constantcontact'
gem 'omniauth-constantcontact2'
gem 'omniauth-coinbase'
##gem 'omniauth-coursera'
##gem 'omniauth_crowd'
#gem 'omniauth-dailymile'
##gem 'omniauth-dailymotion'
gem 'omniauth-dash'
gem 'omniauth-deezer'
gem 'omniauth-desk'
##gem 'omniauth-deviantart'
gem 'omniauth-disqus'
gem 'omniauth-digitalocean'
##gem 'omniauth-do'
#gem 'omniauth-doximity'
gem 'omniauth-dribbble', github: 'excid3/omniauth-dribbble', branch: "patch-1"
gem 'omniauth-dwolla'
##gem 'omniauth-dropbox'
gem 'omniauth-dropbox-oauth2'
gem 'omniauth-ebay'
#gem 'omniauth-empireavenue'
#gem 'omniauth-crest'
gem 'omniauth-eventbrite'
gem 'omniauth-evernote'
#gem 'omniauth-exvo'
##gem 'omniauth-eyeem'
gem 'omniauth-facebook'
##gem 'omniauth-facebook-access-token'
##gem 'omniauth-familysearch'
##gem 'omniauth-familysearch-identity'
##gem 'omniauth-feedly', github: 'excid3/omniauth-feedly'
#gem 'omniauth-figshare'
gem 'omniauth-fitbit'
gem 'omniauth-flattr'
gem 'omniauth-flickr'
gem 'omniauth-foursquare'
gem 'omniauth-freshbooks'
#gem 'omniauth-geoloqi'
gem 'omniauth-genius'
##gem 'omniauth-getglue'
gem 'omniauth-github'
gem 'omniauth-gitlab'
##gem 'omniauth-goodreads'
##gem 'omniauth-google'
gem 'omniauth-google-oauth2'
##gem 'omniauth-gplus'
##gem 'omniauth-google-apps'
##gem 'omniauth-gotowebinar'
gem 'omniauth-gumroad'
gem 'omniauth-harvest', github: "excid3/omniauth-harvest"
gem 'omniauth-heroku'
##gem 'omniauth-heroku-sso'
##gem 'omniauth-identity'
##gem 'omniauth-igovt'
##gem 'omniauth-imagerelay'
gem 'omniauth-imgur'
#gem 'omniauth-immobilienscout24'
##gem 'omniauth-inbloom'
#gem 'omniauth-indieauth'
gem 'omniauth-instagram'
gem 'omniauth-instapaper'
gem 'omniauth-jawbone'
gem 'omniauth-jira'
#gem 'omniauth-kakao'
#gem 'omniauth-khan-academy'
##gem 'omniauth-kiva'
#gem 'omniauth-klarna'
##gem 'omniauth-klout'
#gem 'omniauth-kongregate'
gem 'omniauth-lastfm'
##gem 'omniauth-launchpad'
##gem 'omniauth-linkedin'
gem 'omniauth-linkedin-oauth2'
##gem 'omniauth-linuxfr.org'
#gem 'omniauth-lockitron'
gem 'omniauth-mailchimp'
##gem 'omniauth-mailru'
#gem 'omniauth-mail_ru'
#gem 'omniauth-mailup'
#gem 'omniauth-mlh'
##gem 'omniauth-marvin'
#gem 'omniauth-mendeley'
gem 'omniauth-meetup'
#gem 'omniauth-mercadolibre'
#gem 'omniauth-oauth2'
#gem 'omniauth-healthvault'
##gem 'omniauth-miso'
##gem 'omniauth-mixi'
##gem 'omniauth-mydigipass'
#gem 'omniauth-moves'
##gem 'omniauth-myob'
#gem 'omniauth-myspace'
#gem 'omniauth-namba'
##gem 'omniauth-naver'
##gem 'omniauth-ncu'
##gem 'omniauth-nest'
##gem 'omniauth-netatmo'
gem 'omniauth-netflix'
##gem 'omniauth-nk'
#gem 'omniauth-odnoklassniki'
#gem 'omniauth-office365'
#gem 'omniauth-ohloh'
#gem 'omniauth-osm'
##gem 'omniauth-opinionage'
##gem 'omniauth-origo'
#gem 'omniauth-outrightmental'
#gem 'omniauth-path'
gem 'omniauth-paypal', github: 'excid3/omniauth-paypal'
gem 'omniauth-paymill'
##gem 'omniauth-phabricator'
gem 'omniauth-photobucket'
##gem 'omniauth-picplz'
#gem 'omniauth-piryx'
gem 'omniauth-producthunt', github: 'lukaszkorecki/omniauth-producthunt'
##gem 'omniauth-podio'
##gem 'omniauth_qiita'
##gem 'omniauth-qq'
gem 'omniauth-quickbooks'
##gem 'omniauth-rdio'
gem 'omniauth-rdio-oauth2'
##gem 'omniauth-repp'
#gem 'omniauth-xiaonei'
##gem 'omniauth-roomorama'
#gem 'omniauth-rtm'
#gem 'omniauth-redbooth'
#gem 'omniauth-rightsignature'
##gem 'omniauth-runkeeper'
##gem 'omniauth-seaconlogistics'
#gem 'omniauth-seesaw'
#gem 'omniauth-sense'
#gem 'omniauth-shapeways'
gem 'omniauth-shopify-oauth2'
#gem 'omniauth-shoplo'
##gem 'omniauth-shopify'
##gem 'omniauth-smarterer'
##gem 'omniauth-smugmug'
#gem 'omniauth-socialstream'
gem 'omniauth-soundcloud', github: 'moomerman/omniauth-soundcloud'
#gem 'omniauth-soup'
gem 'omniauth-spotify'
##gem 'omniauth-stackexchange'
##gem 'omniauth-stagebloc'
#gem 'omniauth-strava'
gem 'omniauth-stripe-connect'
##gem 'omniauth-salesforce'
##gem 'omniauth-svpply'
#gem 'omniauth-37signals'
gem 'omniauth-steam'
##gem 'omniauth-taskrabbit'
##gem 'omniauth-thecity'
#gem 'omniauth-ticketbud'
#gem 'omniauth-toshl'
#gem 'omniauth-tradegecko'
#gem 'omniauth-tradeking'
gem 'omniauth-trello'
##gem 'omniauth-troopid'
gem 'omniauth-tumblr'
gem 'omniauth-twitch'
gem 'omniauth-twitter'
gem 'omniauth-uber'
##gem 'omniauth-ubiregi'
#gem 'omniauth-viadeo'
gem 'omniauth-venmo'
gem 'omniauth-vimeo'
#gem 'omniauth-vkontakte'
##gem 'omniauth-wechat-oauth2'
##gem 'omniauth-weibo'
#gem 'omniauth-weibo-oauth2'
gem 'omniauth-windowslive'
##gem 'omniauth-withings'
#gem 'omniauth-wordpress_hosted', github: 'jwickard/omniauth-wordpress-oauth2-plugin'
gem 'omniauth-xero'
#gem 'omniauth-xing'
gem 'omniauth-yahoo'
gem 'omniauth-yammer'
##gem 'omniauth-yubikey'
##gem 'omniauth-yandex'
#gem 'omniauth-youtube'
#gem 'oa-webmoney'
##gem 'omniauth-wepay'
gem 'omniauth-zendesk'
##gem 'omniauth-zenpayroll'

#gem 'omniauth-joinme', path: "/Users/chris/code/omniauth-joinme"
