PROVIDERS = [
  ["twenty_three_and_me", "23andMe", "https://github.com/dluxemburg/omniauth-23andme", "23andme.com", "https://api.23andme.com/apply/"],
  ["fiveHundredPx", "500px", "https://github.com/arthurnn/omniauth-500px", "500px.com", "https://500px.com/settings/applications"],
  #["affinitylive", "AffinityLive", "https://github.com/rikkipitt/omniauth-affinitylive", "affinitylive.com"],
  ["amazon", "Amazon", "https://github.com/wingrunr21/omniauth-amazon", "amazon.com", "https://sellercentral.amazon.com/gp/homepage.html"],
  ["angellist", "AngelList", "https://github.com/railsjedi/omniauth-angellist", "angellist.co", "https://angel.co/api/oauth/clients"],
  ##["aol", "Aol/AIM", "https://github.com/pianosnake/omniauth-aol", "aol.com"],
  ["appnet", "App.net", "https://github.com/phuu/omniauth-appnet", "app.net", "https://account.app.net/developer/apps/"],
  ##["appfigures", "AppFigures", "https://github.com/Triaged/omniauth-appfigures", "appfigures.com"],
  #["auphonic", "Auphonic", "https://github.com/fliiiix/omniauth-auphonic", "auphonic.com"],
  ##["auth0", "Auth0", "https://github.com/auth0/omniauth-auth0", "auth0.com"],
  ["automatic", "Automatic", "https://github.com/Automatic/omniauth-automatic", "automatic.com", "https://developer.automatic.com/my-apps"],
  ##["arcgis", "ArcGIS Online", "https://github.com/Esri/omniauth-arcgis", "arcgis.com"],
  #["authic", "Authic", "https://github.com/authic/omniauth-authic", "authic.com"],
  ##["azure-activedirectory", "AzureAD", "https://github.com/AzureAD/omniauth-azure-activedirectory", "azure.microsoft.com"],
  ["azure_oauth2", "Azure", "https://github.com/KonaTeam/omniauth-azure-oauth2", "azure.microsoft.com", "http://msdn.microsoft.com/en-us/library/azure/dn132599.aspx"],
  ##["behance", "Behance", "https://github.com/sandboxws/omniauth-behance", "behance.com"],
  #["bike_index", "Bike Index", "https://github.com/bikeindex/omniauth-bike-index", "bikeindex.org"],
  ## SITE IS UNAVAILABLE ["thebase", "BASE", "https://github.com/stockflow/omniauth-thebase", "thebase.com"],
  #["bigcartel", "Bigcartel", "https://github.com/citizens/omniauth-bigcartel", "bigcartel.com"],
  ["bitly", "Bitly", "https://github.com/michaeldelorenzo/omniauth-bitly", "bit.ly", "https://bitly.com/a/oauth_apps"],
  ##["bitrix24", "Bitrix24", "https://github.com/crsde/omniauth-bitrix24", "bitrix24.com"],
  #["box", "Box.net", "https://github.com/mbleigh/omniauth-box", "box.net"],
  ["box", "Box", "https://github.com/icoretech/omniauth-box2", "box.net", "https://app.box.com/developers/services"],
  #["browser_id", "BrowserID", "https://github.com/intridea/omniauth-browserid", "identity.mozilla.com"],
  #["broadworks", "BroadWorks", "https://github.com/janx/omniauth-broadworks", "broadsoft.com"],
  ##["buffer", "Buffer", "https://github.com/rdsoze/omniauth-buffer", "buffer.com"],
  ["buffer", "Buffer", "https://github.com/bufferapp/omniauth-buffer2", "buffer.com", "https://buffer.com/developers/apps"],
  #["cacoo", "Cacoo", "https://github.com/bonsaiben/omniauth-cacoo", "cacoo.com"],
  #["createsend", "Campaign Monitor", "https://github.com/jdennes/omniauth-createsend", "campaignmonitor.com"],
  ##["cheddar", "Cheddar", "https://github.com/willrax/omniauth-cheddar", "cheddar.com"],
  ["clef", "Clef", "https://github.com/jessepollak/omniauth-clef", "getclef.com", "https://getclef.com/developer"],
  #["cloud66", "Cloud 66", "https://github.com/rastasheep/omniauth-cloud66", "cloud66.com"],
  ##["cloudsdale", "Cloudsdale", "https://github.com/IOMUSE/omniauth-cloudsdale", "cloudsdale.com"],
  ["cobot", "Cobot", "https://github.com/cobot/omniauth_cobot", "cobot.me", "https://www.cobot.me/oauth2_clients"],
  ["concur", "Concur", "https://github.com/dkastner/omniauth-concur", "concur.com", "https://developer.concur.com/manage-apps/register.html"],
  #["cloudfoundry", "Cloud Foundry", "https://github.com/cloudfoundry/omniauth-uaa-oauth2", "cloudfoundry.org"],
  ##["constantcontact", "ConstantContact", "https://github.com/calebclark/omniauth-constantcontact"],
  ["constantcontact", "Constant Contact", "https://github.com/asanghi/omniauth-constantcontact2", "constantcontact.com", "https://constantcontact.mashery.com/apps/"],
  ["coinbase", "Coinbase", "https://github.com/coinbase/omniauth-coinbase", "coinbase.com", "https://www.coinbase.com/settings/api"],
  ##["coursera", "Coursera", "https://github.com/leoromanovsky/omniauth-coursera", "coursera.org"],
  ##["crowd", "Crowd", "https://github.com/robdimarco/omniauth_crowd"],
  #["dailymile", "DailyMile", "https://github.com/hampei/omniauth-dailymile", "dailymile.com"],
  ##["dailymotion", "Dailymotion", "https://github.com/slainer68/omniauth-dailymotion"],
  ["dash", "Dash", "https://github.com/aren55555/omniauth-dash", "dash.by", "https://dash.by/developers.html"],
  ["deezer", "Deezer", "https://github.com/geoffroymontel/omniauth-deezer", "deezer.com", "http://developers.deezer.com/"],
  ["desk", "Desk.com", "https://github.com/tstachl/omniauth-desk", "desk.com", "http://dev.desk.com/guides/oauth/"],
  ##["deviantart", "DeviantART", "https://github.com/Zeeraw/omniauth-deviantart", "deviantart.com"],
  ["disqus", "Disqus", "https://github.com/clexmond/omniauth-disqus", "disqus.com", "https://disqus.com/api/applications/"],
  ["digitalocean", "DigitalOcean", "https://github.com/digitaloceancloud/omniauth-digitalocean", "digitalocean.com", "https://cloud.digitalocean.com/settings/applications/#dev-apps"],
  ##["do", "Do", "https://github.com/Do/omniauth-do", "do.com"],
  #["doximity", "Doximity", "https://github.com/huyha85/omniauth-doximity", "doximity.com"],
  ["dribbble", "Dribbble", "https://github.com/adamjspooner/omniauth-dribbble", "dribbble.com", "https://dribbble.com/account/applications"],
  ["dwolla", "Dwolla", "https://github.com/jeffersongirao/omniauth-dwolla", "dwolla.com", "https://www.dwolla.com/applications"],
  ##["dropbox", "Dropbox", "https://github.com/spagalloco/omniauth-dropbox", "dropbox.com"],
  ["dropbox_oauth2", "Dropbox", "https://github.com/bamorim/omniauth-dropbox-oauth2", "dropbox.com", "https://www.dropbox.com/developers/apps/"],
  ["ebay", "eBay", "https://github.com/TheGiftsProject/omniauth-ebay", "ebay.com"],
  #["empireavenue", "Empire Avenue", "https://github.com/txwikinger/omniauth-empireavenue", "empire.kred"],
  #["crest", "EVE Online/CREST", "https://github.com/mhutter/omniauth-crest", "eveonline.com"],
  ["eventbrite", "Eventbrite", "https://github.com/k504866430/omniauth-eventbrite", "eventbrite.com"],
  ["evernote", "Evernote", "https://github.com/szimek/omniauth-evernote", "evernote.com"],
  #["exvo", "Exvo", "https://github.com/exvo/omniauth-exvo", "tolq.com"],
  ##["eyeem", "EyeEm", "https://github.com/Varek/omniauth-eyeem", "eyeem.com"],
  ["facebook", "Facebook", "https://github.com/mkdynamic/omniauth-facebook", "facebook.com"],
  ##["facebook-access-token", "Facebook Access Token", "https://github.com/SoapSeller/omniauth-facebook-access-token"],
  ##["familysearch", "FamilySearch", "https://github.com/xrkhill/omniauth-familysearch"],
  ##["familysearch-identity", "FamilySearch Identity", "https://github.com/xrkhill/omniauth-familysearch-identity"],
  ##["feedly", "Feedly", "https://github.com/johnmpotter/omniauth-feedly", "feedly.com"],
  #["figshare", "Figshare", "https://github.com/jdleesmiller/omniauth-figshare", "figshare.com"],
  ["fitbit", "Fitbit", "https://github.com/tkgospodinov/omniauth-fitbit", "fitbit.com"],
  ["flattr", "Flattr", "https://github.com/smgt/omniauth-flattr", "flattr.com"],
  ["flickr", "Flickr", "https://github.com/timbreitkreutz/omniauth-flickr", "flickr.com"],
  ["foursquare", "Foursquare", "https://github.com/arunagw/omniauth-foursquare", "foursquare.com"],
  ["freshbooks", "FreshBooks", "https://github.com/fdeschenes/omniauth-freshbooks", "freshbooks.com"],
  #["geoloqi", "Geoloqi", "https://github.com/geoloqi/omniauth-geoloqi", "geoloqi.com"],
  ["genius", "Genius", "https://github.com/Genius/omniauth-genius", "genius.com"],
  ##["getglue", "GetGlue", "https://github.com/JCBarry/omniauth-getglue", "getglue.com"],
  ["github", "GitHub", "https://github.com/intridea/omniauth-github", "github.com"],
  ["gitlab", "GitLab", "https://github.com/linchus/omniauth-gitlab", "gitlab.com"],
  ##["goodreads", "Goodreads", "https://github.com/sandboxws/omniauth-goodreads", "goodreads.com"],
  ##["google", "Google", "https://github.com/Yesware/omniauth-google", "google.com"],
  ["google_oauth2", "Google", "https://github.com/zquestz/omniauth-google-oauth2", "google.com"],
  ##["gplus", "Google+", "https://github.com/krainboltgreene/omniauth-gplus"],
  ##["google-apps", "Google Apps", "https://github.com/sishen/omniauth-google-apps"],
  ##["gotowebinar", "GoToWebinar", "https://github.com/grandall/omniauth-gotowebinar"],
  ["gumroad", "Gumroad", "https://github.com/gumroad/omniauth-gumroad", "gumroad.com"],
  ["harvest", "Harvest", "https://github.com/corewebdesign/omniauth-harvest", "getharvest.com"],
  ["heroku", "Heroku", "https://github.com/heroku/omniauth-heroku", "heroku.com"],
  ##["heroku-sso", "Heroku Provider SSO", "https://github.com/stvp/omniauth-heroku-sso", "heroku.com"],
  ##["identity", "Identity", "https://github.com/intridea/omniauth-identity"],
  ##["igovt", "igovt", "https://github.com/nationallibrarynz/omniauth-igovt"],
  ##["imagerelay", "Image Relay", "https://github.com/imagerelay/omniauth-imagerelay"],
  ["imgur", "Imgur", "https://github.com/kirkokada/omniauth-imgur", "imgur.com"],
  #["immobilienscout24", "ImmobilienScout24", "https://github.com/endil/omniauth-immobilienscout24", "immobilienscout24.de"],
  ##["inbloom", "inBloom", "https://github.com/khoffma4/omniauth-inbloom"],
  #["indieauth", "IndieAuth", "https://github.com/aaronpk/omniauth-indieauth", "indieauth.com"],
  ["instagram", "Instagram", "https://github.com/ropiku/omniauth-instagram", "instagram.com"],
  ["instapaper", "Instapaper", "https://github.com/spagalloco/omniauth-instapaper", "instapaper.com"],
  ["jawbone", "Jawbone", "https://github.com/ruthienachmany/omniauth-jawbone", "jawbone.com"],
  ["jira", "JIRA", "https://github.com/rmanalan/omniauth-jira", "jira.com"],
  #["kakao", "Kakao", "https://github.com/shaynekang/omniauth-kakao", "kakao.com"],
  #["khan_academy", "Khan Academy", "https://github.com/dipil-saud/omniauth-khan-academy", "khanacademy.org"],
  ##["kiva", "Kiva.org", "https://github.com/kiva/omniauth-kiva", "kiva.org"],
  #["klarna", "Klarna", "https://github.com/klarna/omniauth-klarna", "klarna.com"],
  ##["klout", "Klout", "https://github.com/heeton/omniauth-klout", "klout.com"],
  #["kongregate", "Kongregate", "https://github.com/uken/omniauth-kongregate", "kongregate.com"],
  ["lastfm", "Last.FM", "https://github.com/masterkain/omniauth-lastfm", "last.fm"],
  ##["launchpad", "Launchpad", "https://github.com/joaopapereira/omniauth-launchpad", "launchpad.net"],
  ##["linkedin", "LinkedIn", "https://github.com/skorks/omniauth-linkedin", "linkedin.com"],
  ["linkedin", "LinkedIn OAuth2", "https://github.com/decioferreira/omniauth-linkedin-oauth2", "linkedin.com"],
  ##["linuxfr.org", "LinuxFr.org", "https://github.com/nono/omniauth-linuxfr.org", "linuxfr.org"],
  #["lockitron", "Lockitron", "https://github.com/kurtisnelson/omniauth-lockitron", "lockitron.com"],
  ["mailchimp", "Mailchimp", "https://github.com/floomoon/omniauth-mailchimp", "mailchimp.com"],
  ##["mailru", "Mail.ru", "https://github.com/gumayunov/omniauth-mailru"],
  #["mail_ru", "Mail.ru", "https://github.com/andrey-skat/omniauth-mail_ru", "mail.ru"],
  #["mailup", "MailUp", "https://github.com/mailup/omniauth-mailup", "mailup.com"],
  #["mlh", "Major League Hacking", "https://github.com/mlh/omniauth-mlh", "mlh.io"],
  ##["marvin", "Marvin", "https://github.com/fakenine/omniauth-marvin"],
  #["mendeley", "Mendeley.com", "https://github.com/hedgesky/omniauth-mendeley", "mendeley.com"],
  ["meetup", "Meetup.com", "https://github.com/tapster/omniauth-meetup", "meetup.com"],
  #["mercadolibre", "MercadoLibre.com", "https://github.com/gullitmiranda/omniauth-mercadolibre", "mercadolibre.com"],
  #["oauth2", "Michigan State University", "https://github.com/Michigan-State-University/omniauth-oauth2", "msu.edu"],
  #["healthvault", "Microsoft HealthVault", "https://github.com/Antiarchitect/omniauth-healthvault", "healthvault.com"],
  ##["miso", "Miso", "https://github.com/judearasu/omniauth-miso"],
  ##["mixi", "mixi", "https://github.com/mixi-inc/omniauth-mixi"],
  ##["mydigipass", "Mydigipass.com", "https://github.com/vasco-data-security/omniauth-mydigipass"],
  #["moves", "Moves", "https://github.com/nickelser/omniauth-moves", "moves-app.com"],
  ##["myob", "MYOB", "https://github.com/davidlumley/omniauth-myob"],
  #["myspace", "MySpace", "https://github.com/johnf/omniauth-myspace", "myspace.com"],
  #["namba", "Namba", "https://github.com/ZeroOneStudio/omniauth-namba", "namba.net"],
  ##["naver", "Naver", "https://github.com/kimsuelim/omniauth-naver"],
  ##["ncu", "NCU", "https://github.com/NCUNOS/omniauth-ncu"],
  ##["nest", "Nest", "https://github.com/nestlabs/omniauth-nest"],
  ##["netatmo", "Netatmo", "https://github.com/vincent-pochet/omniauth-netatmo"],
  ["netflix", "Netflix", "https://github.com/spagalloco/omniauth-netflix", "netflix.com"],
  ##["nk", "nk.pl", "https://github.com/naszaklasa/omniauth-nk"],
  ##["odnoklassniki", "Odnoklassniki", "https://github.com/incubus/omniauth-odnoklassniki"],
  #["office365", "Office 365", "https://github.com/simi/omniauth-office365", "office.com"],
  #["ohloh", "Ohloh", "https://github.com/RodrigoAyala/omniauth-ohloh", "openhub.net"],
  #["osm", "OpenStreetMap", "https://github.com/sozialhelden/omniauth-osm", "openstreetmap.org"],
  ##["opinionage", "Opinionage", "https://github.com/opinionage/omniauth-opinionage"],
  ##["origo", "Origo", "https://github.com/bengler/omniauth-origo"],
  #["outrightmental", "Outright Mental", "https://github.com/outrightmental/omniauth-outrightmental", "outright.io"],
  #["path", "Path", "https://github.com/KentoMoriwaki/omniauth-path", "path.com"],
  ["paypal", "PayPal", "https://github.com/datariot/omniauth-paypal", "paypal.com"],
  ["paymill", "Paymill", "https://github.com/groupbuddies/omniauth-paymill", "paymill.com"],
  ##["phabricator", "Phabricator", "https://github.com/dgvz/omniauth-phabricator"],
  ["photobucket", "Photobucket", "https://github.com/zef/omniauth-photobucket", "photobucket.com"],
  ##["picplz", "Picplz", "https://github.com/arunagw/omniauth-picplz"],
  #["piryx", "Piryx", "https://github.com/SparkartGroupInc/omniauth-piryx", "piryx.com"],
  ["producthunt", "Producthunt", "https://github.com/lukaszkorecki/omniauth-producthunt", "producthunt.com"],
  ##["podio", "Podio", "https://github.com/lucasallan/omniauth-podio"],
  ##["omniauth_qiita", "Qiita", "https://github.com/tmiyamon/omniauth_qiita"],
  ##["qq", "QQ", "https://github.com/beenhero/omniauth-qq"],
  ["quickbooks", "Quickbooks", "https://github.com/davidlumley/omniauth-quickbooks", "quickbooks.com"],
  ##["rdio", "Rdio", "https://github.com/nixme/omniauth-rdio"],
  ["rdio_oauth2", "Rdio OAuth2", "https://github.com/robertlong/omniauth-rdio-oauth2", "rdio.com"],
  ##["repp", "Repp", "https://github.com/Kandidly/omniauth-repp"],
  ##["xiaonei", "Renren", "https://github.com/lastomato/omniauth-xiaonei"],
  ##["roomorama", "Roomorama", "https://github.com/BookingSync/omniauth-roomorama"],
  #["rtm", "Remember The Milk", "https://github.com/nicck/omniauth-rtm", "rememberthemilk.com"],
  #["redbooth", "Redbooth", "https://github.com/teambox/omniauth-redbooth", "redbooth.com"],
  #["rightsignature", "RightSignature", "https://github.com/DeepikaaSubramaniam21/omniauth-rightsignature", "rightsignature.com"],
  ##["runkeeper", "RunKeeper", "https://github.com/m4i/omniauth-runkeeper"],
  ##["seaconlogistics", "Seacon Logistics", "https://github.com/kabisaict/omniauth-seaconlogistics"],
  ## SEEMS MISSING ["seesaw", "Seesaw", "https://github.com/seesawco/omniauth-seesaw", "web.seesaw.me"],
  #["sense", "Sense", "https://github.com/senseobservationsystems/omniauth-sense", "sense-labs.com"],
  #["shapeways", "Shapeways", "https://github.com/phy5ics/omniauth-shapeways", "shapeways.com"],
  ["shopify", "Shopify", "https://github.com/Shopify/omniauth-shopify-oauth2", "shopify.com"],
  #["shoplo", "Shoplo", "https://github.com/msojda/omniauth-shoplo", "shoplo.com"],
  ##["shopify", "Shopify Legacy", "https://github.com/yevgenko/omniauth-shopify"],
  ##["smarterer", "Smarterer", "https://github.com/sandboxws/omniauth-smarterer"],
  ##["smugmug", "SmugMug", "https://github.com/BirdBox/omniauth-smugmug"],
  #["socialstream", "Social Stream", "https://github.com/ging/omniauth-socialstream", "social-stream.dit.upm.es"],
  ["soundcloud", "SoundCloud", "https://github.com/soundcloud/omniauth-soundcloud", "soundcloud.com"],
  #["soup", "Soup.io", "https://github.com/fliiiix/omniauth-soup", "soup.io"],
  ["spotify", "Spotify", "https://github.com/icoretech/omniauth-spotify", "spotify.com"],
  ##["stackexchange", "StackExchange", "https://github.com/nashby/omniauth-stackexchange"],
  ##["stagebloc", "StageBloc", "https://github.com/TheCodeDeli/omniauth-stagebloc"],
  #["strava", "Strava", "https://github.com/thogg4/omniauth-strava", "strava.com"],
  ["stripe_connect", "Stripe Connect", "https://github.com/isaacsanders/omniauth-stripe-connect", "stripe.com"],
  ##["salesforce", "salesforce", "https://github.com/realdoug/omniauth-salesforce", "salesforce.com"],
  ##["svpply", "Svpply", "https://github.com/Svpply/omniauth-svpply"],
  #["37signals", "37signals", "https://github.com/tallgreentree/omniauth-37signals", "basecamp.com"],
  ["steam", "Steam", "https://github.com/reu/omniauth-steam", "store.steampowered.com"],
  ##["taskrabbit", "TaskRabbit", "https://github.com/jrichardlai/omniauth-taskrabbit"],
  ##["thecity", "The City", "https://github.com/thecity/omniauth-thecity"],
  #["ticketbud", "Ticketbud", "https://github.com/Ticketbud/omniauth-ticketbud", "ticketbud.com"],
  #["toshl", "Toshl", "https://github.com/h2ocube/omniauth-toshl", "toshl.com"],
  #["tradegecko", "TradeGecko", "https://github.com/tradegecko/omniauth-tradegecko", "tradegecko"],
  #["tradeking", "TradeKing", "https://github.com/JCBarry/omniauth-tradeking", "tradeking.com"],
  ["trello", "Trello", "https://github.com/joshrowley/omniauth-trello", "trello.com"],
  ##["troopid", "Troop ID", "https://github.com/troopswap/omniauth-troopid"],
  ["tumblr", "Tumblr", "https://github.com/jamiew/omniauth-tumblr", "tumblr.com"],
  ["twitch", "Twitch.TV", "https://github.com/WebTheoryLLC/omniauth-twitch", "twitch.tv", "http://www.twitch.tv/kraken/oauth2/clients/new"],
  ["twitter", "Twitter", "https://github.com/arunagw/omniauth-twitter", "twitter.com"],
  ["uber", "Uber", "https://github.com/tmilewski/omniauth-uber", "uber.com"],
  ##["ubiregi", "Ubiregi", "https://github.com/stockflow/omniauth-ubiregi"],
  #["viadeo", "Viadeo", "https://github.com/Pasta/omniauth-viadeo", "viadeo.com"],
  ["venmo", "Venmo", "https://github.com/tmilewski/omniauth-venmo", "venmo.com"],
  ["vimeo", "Vimeo", "https://github.com/beanieboi/omniauth-vimeo", "vimeo.com"],
  #["vkontakte", "Vkontakte", "https://github.com/mamantoha/omniauth-vkontakte", "vk.com"],
  ##["wechat-oauth2", "Wechat", "https://github.com/skinnyworm/omniauth-wechat-oauth2"],
  ##["weibo", "Weibo", "https://github.com/jihao/omniauth-weibo"],
  #["weibo", "Weibo OAuth2", "https://github.com/beenhero/omniauth-weibo-oauth2", "weibo.com"],
  ["windowslive", "Windows Live ID", "https://github.com/joel/omniauth-windowslive", "microsoft.com"],
  ##["withings", "Withings", "https://github.com/bsoule/omniauth-withings"],
  #["wordpress_hosted", "Wordpress Oauth2 Provider", "https://github.com/jwickard/omniauth-wordpress-oauth2-plugin", "wordpress.com"],
  ["xero", "Xero", "https://github.com/kaleworsley/omniauth-xero", "xero.com"],
  #["xing", "XING", "https://github.com/roccoblues/omniauth-xing", "xing.com"],
  ["yahoo", "Yahoo", "https://github.com/timbreitkreutz/omniauth-yahoo", "yahoo.com"],
  ["yammer", "Yammer", "https://github.com/le0pard/omniauth-yammer", "yammer.com"],
  ##["yubikey", "Yubikey", "https://github.com/steveh/omniauth-yubikey"],
  ##["yandex", "Yandex", "https://github.com/evrone/omniauth-yandex"],
  ##["youtube", "YouTube", "https://github.com/jamiew/omniauth-youtube"],
  #["google_oauth2", "YouTube", "https://github.com/zquestz/omniauth-google-oauth2", "youtube.com"],
  #["webmoney", "WebMoney", "https://github.com/skyeagle/oa-webmoney", "wmtransfer.com"],
  ##["wepay", "WePay", "https://github.com/tenaciousflea/omniauth-wepay"],
  ["zendesk", "Zendesk", "https://github.com/tstachl/omniauth-zendesk", "zendesk.com"],
  ##["zenpayroll", "zenpayroll", "https://github.com/shiftdock/omniauth-zenpayroll"],
  ##
  #["joinme", "Join.me", "https://github.com/excid3/omniauth-joinme", "join.me"],
]
