providers = [
  ["twenty_three_and_me", "23andMe", "https://github.com/dluxemburg/omniauth-23andme"],
  ["fiveHundredPx", "500px", "https://github.com/arthurnn/omniauth-500px"],
  ["affinitylive", "AffinityLive", "https://github.com/rikkipitt/omniauth-affinitylive"],
  #["amazon", "Amazon", "https://github.com/wingrunr21/omniauth-amazon"],
  ["angellist", "AngelList", "https://github.com/railsjedi/omniauth-angellist"],
  #["aol", "Aol/AIM", "https://github.com/pianosnake/omniauth-aol"],
  ["appnet", "App.net", "https://github.com/phuu/omniauth-appnet"],
  #["appfigures", "AppFigures", "https://github.com/Triaged/omniauth-appfigures"],
  ["auphonic", "Auphonic", "https://github.com/fliiiix/omniauth-auphonic"],
  #["auth0", "Auth0", "https://github.com/auth0/omniauth-auth0"],
  ["automatic", "Automatic", "https://github.com/Automatic/omniauth-automatic"],
  #["arcgis", "ArcGIS Online", "https://github.com/Esri/omniauth-arcgis"],
  ["authic", "Authic", "https://github.com/authic/omniauth-authic"],
  #["azure-activedirectory", "AzureAD", "https://github.com/AzureAD/omniauth-azure-activedirectory"],
  ["azure_oauth2", "Azure", "https://github.com/KonaTeam/omniauth-azure-oauth2"],
  #["behance", "Behance", "https://github.com/sandboxws/omniauth-behance"],
  ["bike_index", "Bike Index", "https://github.com/bikeindex/omniauth-bike-index"],
  ["thebase", "BASE", "https://github.com/stockflow/omniauth-thebase"],
  ["bigcartel", "Bigcartel", "https://github.com/citizens/omniauth-bigcartel"],
  #["bitly", "Bitly", "https://github.com/michaeldelorenzo/omniauth-bitly"],
  #["bitrix24", "Bitrix24", "https://github.com/crsde/omniauth-bitrix24"],
  ["box", "Box.net", "https://github.com/mbleigh/omniauth-box"],
  #["box2", "Box", "https://github.com/icoretech/omniauth-box2"],
  ["browser_id", "BrowserID", "https://github.com/intridea/omniauth-browserid"],
  ["broadworks", "BroadWorks", "https://github.com/janx/omniauth-broadworks"],
  #["buffer", "Buffer", "https://github.com/rdsoze/omniauth-buffer"],
  #["buffer2", "Buffer2", "https://github.com/bufferapp/omniauth-buffer2"],
  ["cacoo", "Cacoo", "https://github.com/bonsaiben/omniauth-cacoo"],
  ["createsend", "Campaign Monitor", "https://github.com/jdennes/omniauth-createsend"],
  #["cheddar", "Cheddar", "https://github.com/willrax/omniauth-cheddar"],
  ["clef", "Clef", "https://github.com/jessepollak/omniauth-clef"],
  ["cloud66", "Cloud 66", "https://github.com/rastasheep/omniauth-cloud66"],
  #["cloudsdale", "Cloudsdale", "https://github.com/IOMUSE/omniauth-cloudsdale"],
  ["cobot", "Cobot", "https://github.com/cobot/omniauth_cobot"],
  ["concur", "Concur", "https://github.com/dkastner/omniauth-concur"],
  ["cloudfoundry", "Cloud Foundry", "https://github.com/cloudfoundry/omniauth-uaa-oauth2"],
  #["constantcontact", "ConstantContact", "https://github.com/calebclark/omniauth-constantcontact"],
  ["constantcontact", "ConstantContact2", "https://github.com/asanghi/omniauth-constantcontact2"],
  ["coinbase", "Coinbase", "https://github.com/coinbase/omniauth-coinbase"],
  #["coursera", "Coursera", "https://github.com/leoromanovsky/omniauth-coursera"],
  #["crowd", "Crowd", "https://github.com/robdimarco/omniauth_crowd"],
  ["dailymile", "DailyMile", "https://github.com/hampei/omniauth-dailymile"],
  #["dailymotion", "Dailymotion", "https://github.com/slainer68/omniauth-dailymotion"],
  ["dash", "Dash", "https://github.com/aren55555/omniauth-dash"],
  ["deezer", "Deezer", "https://github.com/geoffroymontel/omniauth-deezer"],
  ["desk", "Desk.com", "https://github.com/tstachl/omniauth-desk"],
  #["deviantart", "DeviantART", "https://github.com/Zeeraw/omniauth-deviantart"],
  #["disqus", "Disqus", "https://github.com/clexmond/omniauth-disqus"],
  ["digitalocean", "DigitalOcean", "https://github.com/digitaloceancloud/omniauth-digitalocean"],
  #["do", "Do", "https://github.com/Do/omniauth-do"],
  ["doximity", "Doximity", "https://github.com/huyha85/omniauth-doximity"],
  ["dribbble", "Dribbble", "https://github.com/adamjspooner/omniauth-dribbble"],
  ["dwolla", "Dwolla", "https://github.com/jeffersongirao/omniauth-dwolla"],
  #["dropbox", "Dropbox", "https://github.com/spagalloco/omniauth-dropbox"],
  ["dropbox_oauth2", "Dropbox OAuth2", "https://github.com/bamorim/omniauth-dropbox-oauth2"],
  ["ebay", "eBay", "https://github.com/TheGiftsProject/omniauth-ebay"],
  ["empireavenue", "Empire Avenue", "https://github.com/txwikinger/omniauth-empireavenue"],
  ["crest", "EVE Online/CREST", "https://github.com/mhutter/omniauth-crest"],
  ["eventbrite", "Eventbrite", "https://github.com/k504866430/omniauth-eventbrite"],
  ["evernote", "Evernote", "https://github.com/szimek/omniauth-evernote"],
  ["exvo", "Exvo", "https://github.com/exvo/omniauth-exvo"],
  #["eyeem", "EyeEm", "https://github.com/Varek/omniauth-eyeem"],
  ["facebook", "Facebook", "https://github.com/mkdynamic/omniauth-facebook"],
  #["facebook-access-token", "Facebook Access Token", "https://github.com/SoapSeller/omniauth-facebook-access-token"],
  #["familysearch", "FamilySearch", "https://github.com/xrkhill/omniauth-familysearch"],
  #["familysearch-identity", "FamilySearch Identity", "https://github.com/xrkhill/omniauth-familysearch-identity"],
  #["feedly", "Feedly", "https://github.com/johnmpotter/omniauth-feedly"],
  ["figshare", "Figshare", "https://github.com/jdleesmiller/omniauth-figshare"],
  ["fitbit", "Fitbit", "https://github.com/tkgospodinov/omniauth-fitbit"],
  ["flattr", "Flattr", "https://github.com/smgt/omniauth-flattr"],
  ["flickr", "Flickr", "https://github.com/timbreitkreutz/omniauth-flickr"],
  ["foursquare", "Foursquare", "https://github.com/arunagw/omniauth-foursquare"],
  ["freshbooks", "FreshBooks", "https://github.com/fdeschenes/omniauth-freshbooks"],
  ["geoloqi", "Geoloqi", "https://github.com/geoloqi/omniauth-geoloqi"],
  ["genius", "Genius", "https://github.com/Genius/omniauth-genius"],
  #["getglue", "GetGlue", "https://github.com/JCBarry/omniauth-getglue"],
  ["github", "GitHub", "https://github.com/intridea/omniauth-github"],
  ["gitlab", "GitLab", "https://github.com/linchus/omniauth-gitlab"],
  #["goodreads", "Goodreads", "https://github.com/sandboxws/omniauth-goodreads"],
  #["google", "Google", "https://github.com/Yesware/omniauth-google"],
  ["google_oauth2", "Google OAuth2", "https://github.com/zquestz/omniauth-google-oauth2"],
  #["gplus", "Google+", "https://github.com/krainboltgreene/omniauth-gplus"],
  #["google-apps", "Google Apps", "https://github.com/sishen/omniauth-google-apps"],
  #["gotowebinar", "GoToWebinar", "https://github.com/grandall/omniauth-gotowebinar"],
  #["gumroad", "Gumroad", "https://github.com/gumroad/omniauth-gumroad"],
  #["harvest", "Harvest", "https://github.com/corewebdesign/omniauth-harvest"],
  #["heroku", "Heroku", "https://github.com/heroku/omniauth-heroku"],
  #["heroku-sso", "Heroku Provider SSO", "https://github.com/stvp/omniauth-heroku-sso"],
  #["identity", "Identity", "https://github.com/intridea/omniauth-identity"],
  #["igovt", "igovt", "https://github.com/nationallibrarynz/omniauth-igovt"],
  #["imagerelay", "Image Relay", "https://github.com/imagerelay/omniauth-imagerelay"],
  ["imgur", "Imgur", "https://github.com/kirkokada/omniauth-imgur"],
  ["immobilienscout24", "ImmobilienScout24", "https://github.com/endil/omniauth-immobilienscout24"],
  #["inbloom", "inBloom", "https://github.com/khoffma4/omniauth-inbloom"],
  ["indieauth", "IndieAuth", "https://github.com/aaronpk/omniauth-indieauth"],
  ["instagram", "Instagram", "https://github.com/ropiku/omniauth-instagram"],
  ["instapaper", "Instapaper", "https://github.com/spagalloco/omniauth-instapaper"],
  ["jawbone", "Jawbone", "https://github.com/ruthienachmany/omniauth-jawbone"],
  ["jira", "JIRA", "https://github.com/rmanalan/omniauth-jira"],
  ["kakao", "Kakao", "https://github.com/shaynekang/omniauth-kakao"],
  ["khan_academy", "Khan Academy", "https://github.com/dipil-saud/omniauth-khan-academy"],
  #["kiva", "Kiva.org", "https://github.com/kiva/omniauth-kiva"],
  ["klarna", "Klarna", "https://github.com/klarna/omniauth-klarna"],
  #["klout", "Klout", "https://github.com/heeton/omniauth-klout"],
  ["kongregate", "Kongregate", "https://github.com/uken/omniauth-kongregate"],
  ["lastfm", "Last.FM", "https://github.com/masterkain/omniauth-lastfm"],
  #["launchpad", "Launchpad", "https://github.com/joaopapereira/omniauth-launchpad"],
  #["linkedin", "LinkedIn", "https://github.com/skorks/omniauth-linkedin"],
  ["linkedin", "LinkedIn OAuth2", "https://github.com/decioferreira/omniauth-linkedin-oauth2"],
  #["linuxfr.org", "LinuxFr.org", "https://github.com/nono/omniauth-linuxfr.org"],
  ["lockitron", "Lockitron", "https://github.com/kurtisnelson/omniauth-lockitron"],
  ["mailchimp", "Mailchimp", "https://github.com/floomoon/omniauth-mailchimp"],
  #["mailru", "Mail.ru", "https://github.com/gumayunov/omniauth-mailru"],
  ["mail_ru", "Mail.ru", "https://github.com/andrey-skat/omniauth-mail_ru"],
  ["mailup", "MailUp", "https://github.com/mailup/omniauth-mailup"],
  ["mlh", "Major League Hacking", "https://github.com/mlh/omniauth-mlh"],
  #["marvin", "Marvin", "https://github.com/fakenine/omniauth-marvin"],
  ["mendeley", "Mendeley.com", "https://github.com/hedgesky/omniauth-mendeley"],
  ["meetup", "Meetup.com", "https://github.com/tapster/omniauth-meetup"],
  ["mercadolibre", "MercadoLibre.com", "https://github.com/gullitmiranda/omniauth-mercadolibre"],
  ["oauth2", "Michigan State University", "https://github.com/Michigan-State-University/omniauth-oauth2"],
  ["healthvault", "Microsoft HealthVault", "https://github.com/Antiarchitect/omniauth-healthvault"],
  #["miso", "Miso", "https://github.com/judearasu/omniauth-miso"],
  #["mixi", "mixi", "https://github.com/mixi-inc/omniauth-mixi"],
  #["mydigipass", "Mydigipass.com", "https://github.com/vasco-data-security/omniauth-mydigipass"],
  ["moves", "Moves", "https://github.com/nickelser/omniauth-moves"],
  #["myob", "MYOB", "https://github.com/davidlumley/omniauth-myob"],
  ["myspace", "MySpace", "https://github.com/johnf/omniauth-myspace"],
  ["namba", "Namba", "https://github.com/ZeroOneStudio/omniauth-namba"],
  #["naver", "Naver", "https://github.com/kimsuelim/omniauth-naver"],
  #["ncu", "NCU", "https://github.com/NCUNOS/omniauth-ncu"],
  #["nest", "Nest", "https://github.com/nestlabs/omniauth-nest"],
  #["netatmo", "Netatmo", "https://github.com/vincent-pochet/omniauth-netatmo"],
  ["netflix", "Netflix", "https://github.com/spagalloco/omniauth-netflix"],
  #["nk", "nk.pl", "https://github.com/naszaklasa/omniauth-nk"],
  ["odnoklassniki", "Odnoklassniki", "https://github.com/incubus/omniauth-odnoklassniki"],
  ["office365", "Office 365", "https://github.com/simi/omniauth-office365"],
  ["ohloh", "Ohloh", "https://github.com/RodrigoAyala/omniauth-ohloh"],
  ["osm", "OpenStreetMap", "https://github.com/sozialhelden/omniauth-osm"],
  #["opinionage", "Opinionage", "https://github.com/opinionage/omniauth-opinionage"],
  #["origo", "Origo", "https://github.com/bengler/omniauth-origo"],
  ["outrightmental", "Outright Mental", "https://github.com/outrightmental/omniauth-outrightmental"],
  ["path", "Path", "https://github.com/KentoMoriwaki/omniauth-path"],
  ["paypal", "PayPal", "https://github.com/datariot/omniauth-paypal"],
  ["paymill", "Paymill", "https://github.com/groupbuddies/omniauth-paymill"],
  #["phabricator", "Phabricator", "https://github.com/dgvz/omniauth-phabricator"],
  ["photobucket", "Photobucket", "https://github.com/zef/omniauth-photobucket"],
  #["picplz", "Picplz", "https://github.com/arunagw/omniauth-picplz"],
  ["piryx", "Piryx", "https://github.com/SparkartGroupInc/omniauth-piryx"],
  ["producthunt", "Producthunt", "https://github.com/lukaszkorecki/omniauth-producthunt"],
  #["podio", "Podio", "https://github.com/lucasallan/omniauth-podio"],
  #["omniauth_qiita", "Qiita", "https://github.com/tmiyamon/omniauth_qiita"],
  #["qq", "QQ", "https://github.com/beenhero/omniauth-qq"],
  ["quickbooks", "Quickbooks", "https://github.com/davidlumley/omniauth-quickbooks"],
  #["rdio", "Rdio", "https://github.com/nixme/omniauth-rdio"],
  ["rdio_oauth2", "Rdio OAuth2", "https://github.com/robertlong/omniauth-rdio-oauth2"],
  #["repp", "Repp", "https://github.com/Kandidly/omniauth-repp"],
  ["xiaonei", "Renren", "https://github.com/lastomato/omniauth-xiaonei"],
  #["roomorama", "Roomorama", "https://github.com/BookingSync/omniauth-roomorama"],
  ["rtm", "Remember The Milk", "https://github.com/nicck/omniauth-rtm"],
  ["redbooth", "Redbooth", "https://github.com/teambox/omniauth-redbooth"],
  ["rightsignature", "RightSignature", "https://github.com/DeepikaaSubramaniam21/omniauth-rightsignature"],
  #["runkeeper", "RunKeeper", "https://github.com/m4i/omniauth-runkeeper"],
  #["seaconlogistics", "Seacon Logistics", "https://github.com/kabisaict/omniauth-seaconlogistics"],
  ["seesaw", "Seesaw", "https://github.com/seesawco/omniauth-seesaw"],
  ["sense", "Sense", "https://github.com/senseobservationsystems/omniauth-sense"],
  ["shapeways", "Shapeways", "https://github.com/phy5ics/omniauth-shapeways"],
  ["shopify", "Shopify", "https://github.com/Shopify/omniauth-shopify-oauth2"],
  ["shoplo", "Shoplo", "https://github.com/msojda/omniauth-shoplo"],
  #["shopify", "Shopify Legacy", "https://github.com/yevgenko/omniauth-shopify"],
  #["smarterer", "Smarterer", "https://github.com/sandboxws/omniauth-smarterer"],
  #["smugmug", "SmugMug", "https://github.com/BirdBox/omniauth-smugmug"],
  ["socialstream", "Social Stream", "https://github.com/ging/omniauth-socialstream"],
  ["soundcloud", "SoundCloud", "https://github.com/soundcloud/omniauth-soundcloud"],
  ["soup", "Soup.io", "https://github.com/fliiiix/omniauth-soup"],
  ["spotify", "Spotify", "https://github.com/icoretech/omniauth-spotify"],
  #["stackexchange", "StackExchange", "https://github.com/nashby/omniauth-stackexchange"],
  #["stagebloc", "StageBloc", "https://github.com/TheCodeDeli/omniauth-stagebloc"],
  ["strava", "Strava", "https://github.com/thogg4/omniauth-strava"],
  ["stripe_connect", "Stripe Connect", "https://github.com/isaacsanders/omniauth-stripe-connect"],
  #["salesforce", "salesforce", "https://github.com/realdoug/omniauth-salesforce"],
  #["svpply", "Svpply", "https://github.com/Svpply/omniauth-svpply"],
  ["37signals", "37signals", "https://github.com/tallgreentree/omniauth-37signals"],
  ["steam", "Steam", "https://github.com/reu/omniauth-steam"],
  #["taskrabbit", "TaskRabbit", "https://github.com/jrichardlai/omniauth-taskrabbit"],
  #["thecity", "The City", "https://github.com/thecity/omniauth-thecity"],
  ["ticketbud", "Ticketbud", "https://github.com/Ticketbud/omniauth-ticketbud"],
  ["toshl", "Toshl", "https://github.com/h2ocube/omniauth-toshl"],
  ["tradegecko", "TradeGecko", "https://github.com/tradegecko/omniauth-tradegecko"],
  ["tradeking", "TradeKing", "https://github.com/JCBarry/omniauth-tradeking"],
  ["trello", "Trello", "https://github.com/joshrowley/omniauth-trello"],
  #["troopid", "Troop ID", "https://github.com/troopswap/omniauth-troopid"],
  ["tumblr", "Tumblr", "https://github.com/jamiew/omniauth-tumblr"],
  #["twitch", "Twitch.TV", "https://github.com/WebTheoryLLC/omniauth-twitch"],
  ["twitter", "Twitter", "https://github.com/arunagw/omniauth-twitter"],
  ["uber", "Uber", "https://github.com/tmilewski/omniauth-uber"],
  #["ubiregi", "Ubiregi", "https://github.com/stockflow/omniauth-ubiregi"],
  ["viadeo", "Viadeo", "https://github.com/Pasta/omniauth-viadeo"],
  ["venmo", "Venmo", "https://github.com/tmilewski/omniauth-venmo"],
  ["vimeo", "Vimeo", "https://github.com/beanieboi/omniauth-vimeo"],
  ["vkontakte", "Vkontakte", "https://github.com/mamantoha/omniauth-vkontakte"],
  #["wechat-oauth2", "Wechat", "https://github.com/skinnyworm/omniauth-wechat-oauth2"],
  #["weibo", "Weibo", "https://github.com/jihao/omniauth-weibo"],
  ["weibo", "Weibo OAuth2", "https://github.com/beenhero/omniauth-weibo-oauth2"],
  ["windowslive", "Windows Live ID", "https://github.com/joel/omniauth-windowslive"],
  #["withings", "Withings", "https://github.com/bsoule/omniauth-withings"],
  ["wordpress_hosted", "Wordpress Oauth2 Provider", "https://github.com/jwickard/omniauth-wordpress-oauth2-plugin"],
  ["xero", "Xero", "https://github.com/kaleworsley/omniauth-xero"],
  ["xing", "XING", "https://github.com/roccoblues/omniauth-xing"],
  ["yahoo", "Yahoo", "https://github.com/timbreitkreutz/omniauth-yahoo"],
  ["yammer", "Yammer", "https://github.com/le0pard/omniauth-yammer"],
  #["yubikey", "Yubikey", "https://github.com/steveh/omniauth-yubikey"],
  #["yandex", "Yandex", "https://github.com/evrone/omniauth-yandex"],
  ["youtube", "YouTube", "https://github.com/jamiew/omniauth-youtube"],
  ["webmoney", "WebMoney", "https://github.com/skyeagle/oa-webmoney"],
  #["wepay", "WePay", "https://github.com/tenaciousflea/omniauth-wepay"],
  ["zendesk", "Zendesk", "https://github.com/tstachl/omniauth-zendesk"],
  #["zenpayroll", "zenpayroll", "https://github.com/shiftdock/omniauth-zenpayroll"],
]

Provider.delete_all

providers.each do |omniauth_name, name, github|
  Provider.where(
    name: name,
    omniauth_name: omniauth_name,
    github: github
  ).first_or_create
end
